on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test-redis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [18.x, 20.x, 22.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: latest

      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test:tsd
      - run: npm run test:cov || npm run test:cov || npm run test:cov

  test-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test cluster
        run: bash test/cluster/docker/main.sh

  test-valkey:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [18.x, 20.x, 22.x]

    services:
      valkey:
        image: valkey/valkey:latest
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test:tsd
      - run: npm run test:cov || npm run test:cov || npm run test:cov

  code-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
